- name: Stop MySQL service
  ansible.builtin.systemd:
    name: "{{ mysql_service_name }}"
    state: stopped
    enabled: no
    daemon_reload: yes
  ignore_errors: yes

- name: Remove MySQL configuration file
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "/etc/profile.d/mysqld.sh"
    - "{{ mysql_config_file }}"
    - "{{ ('/etc/systemd/system/', mysql_service_name ~ '.service' ) | path_join }}"

- name: Remove MySQL deployment directory
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ mysql_log_file | dirname }}"
    - "{{ msyql_socket_file | dirname }}"
    - "{{ mysql_pid_file }}"
    - "{{ mysql_deploy_path }}"
    - "{{ mysql_datadir }}"
